name: Weekly CIDR Update

on:
  schedule:
    - cron: "0 0 * * 0"  # every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  update-cidrs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p Cloudflare Meta OpenAI Mistral Perplexity

      - name: Download Cloudflare IPv4 list
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://www.cloudflare.com/ips-v4/" -o Cloudflare/ipv4.txt
          echo "Cloudflare file size: $(stat -c%s Cloudflare/ipv4.txt) bytes"

      - name: Download Cloudflare IPv6 list
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://www.cloudflare.com/ips-v6/" -o Cloudflare/ipv6.txt
          echo "Cloudflare file size: $(stat -c%s Cloudflare/ipv6.txt) bytes"

      - name: Download Meta (Facebook) Combined GeoFeed
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://www.facebook.com/peering/geofeed" -o Meta/geofeed.csv
          echo "Meta file size: $(stat -c%s Meta/geofeed.csv) bytes"

      - name: Download OpenAI lists
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://openai.com/gptbot.json" -o OpenAI/gptbot.json
          echo "OpenAI GPTBot file size: $(stat -c%s OpenAI/gptbot.json) bytes"

          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://openai.com/searchbot.json" -o OpenAI/searchbot.json
          echo "OpenAI SearchBot file size: $(stat -c%s OpenAI/searchbot.json) bytes"

          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://openai.com/chatgpt-user.json" -o OpenAI/chatgpt-user.json
          echo "OpenAI ChatGPT-User file size: $(stat -c%s OpenAI/chatgpt-user.json) bytes"

          jq -r '.prefixes[].ipv4Prefix' OpenAI/gptbot.json > OpenAI/gptbot.txt
          jq -r '.prefixes[].ipv4Prefix' OpenAI/chatgpt-user.json > OpenAI/chatgpt-user.txt
          jq -r '.prefixes[].ipv4Prefix' OpenAI/searchbot.json > OpenAI/searchbot.txt

      - name: Download Mistral lists
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://mistral.ai/mistralai-user-ips.json" -o Mistral/mistralai-user-ips.json
          echo "Mistral-User file size: $(stat -c%s Mistral/mistralai-user-ips.json) bytes"

          jq -r '.prefixes[].ipv4Prefix' Mistral/mistralai-user-ips.json > Mistral/mistralai-user-ips.txt

      - name: Download Perplexity lists
        run: |
          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://www.perplexity.ai/perplexitybot.json" -o Perplexity/perplexitybot.json
          echo "PerplexityBot file size: $(stat -c%s Perplexity/perplexitybot.json) bytes"

          curl -sSL -L --compressed -A "public-cidrs-bot/1.0" "https://www.perplexity.ai/perplexity-user.json" -o Perplexity/perplexity-user.json
          echo "Perplexity-User file size: $(stat -c%s Perplexity/perplexity-user.json) bytes"

          jq -r '.prefixes[].ipv4Prefix' Perplexity/perplexitybot.json > Perplexity/perplexitybot.txt
          jq -r '.prefixes[].ipv4Prefix' Perplexity/perplexity-user.json > Perplexity/perplexity-user.txt

      - name: Detect and commit individual changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          CHANGED=0

          for path in Cloudflare/ipv4.txt Cloudflare/ipv6.txt Meta/geofeed.csv OpenAI/gptbot.txt OpenAI/chatgpt-user.txt OpenAI/searchbot.txt Mistral/mistralai-user-ips.txt Perplexity/perplexitybot.txt Perplexity/perplexity-user.txt; do
            # Add the file regardless — git will handle new files
            git add "$path"

            # Check if this file has changes or is new
            if ! git diff --cached --quiet -- "$path"; then
              echo "Detected change or new file: $path"
              git commit -m "Update $path - $(date -u +"%Y-%m-%d")"
              CHANGED=1
            fi
          done

          if [ "$CHANGED" -eq 1 ]; then
            git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No changes found."
          fi
